<?php
/**
  * Implements hook_islandora_required_objects()
  * 
  */
function islandora_bioinformatics_genesequence_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_bioinformatics_genesequence');
  $genesequence_cm = $connection->repository->constructObject('islandora:genesequence');
  $genesequence_cm->owner = 'fedoraAdmin';
  $genesequence_cm->label = 'Bioinformatics Genesequence Content Model';
  $genesequence_cm->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $genesequence_cm->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/genesequence_ds_composite_model.xml", FALSE);
  $genesequence_cm->ingestDatastream($datastream);
  return array(
    'islandora_bioinformatics_genesequence' => array(
      'title' => 'Bioinformatics Genesequence',
      'objects' => array(
          $genesequence_cm,
      ),
    ),
  );
}

function islandora_bioinformatics_genesequence_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_bioinformatics_genesequence');
  return array(
    'Genesequence Form' => array(
      'form_file' => "$module_path/xml/islandora_bioinformatics_genesequence_form.xml",
    ),
  );
}

function islandora_bioinformatics_genesequence_islandora_xml_form_builder_form_associations() {
  $module_path = drupal_get_path('module', 'islandora_bioinformatics_genesequence');
  return array(
    'islandora_bioinformatics_genesequence_form' => array(
      'genesequence_cm' => 'islandora:genesequence',
      'form_name' => 'Genesequence Form',
      'dsid' => 'EML',
      'title_field' => array('taxonomy', 'species'),
      'transform' => '',
      //'self_transform' => "$module_path/xml/islandora_bioinformatics_genesequence_transform.xsl",
      'template' => FALSE,
    ),
  );
}
