<?php
/**
  * @file 
  * Implements hook_islandora_required_objects()
  * 
  */
function islandora_lab_object_genesequence_islandora_required_objects(IslandoraTuque $connection) {
  module_load_include('inc', 'islandora_bioinformatics_base', 'base_functions');

  $module_path = drupal_get_path('module', 'islandora_lab_object_genesequence');
  $genesequence_cmodel = $connection->repository->constructObject('islandora:genesequence_cmodel');
  $genesequence_cmodel->owner = 'fedoraAdmin';
  $genesequence_cmodel->label = 'Bioinformatics Genesequence Content Model';
  $genesequence_cmodel->models = 'fedora-system:ContentModel-3.0';
  
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $genesequence_cmodel->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/genesequence_ds_composite_model.xml", FALSE);
  $genesequence_cmodel->ingestDatastream($datastream);
  
  // Trigger-Datastreams Datastream.
  $datastream = $genesequence_cmodel->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/triggers/genesequence_triggers.xml", FALSE);
  $genesequence_cmodel->ingestDatastream($datastream);
  
  //Create relationship with LabObject
  $genesequence_cmodel->relationships->add(FEDORA_MODEL_URI, 'hasModel', 'islandora:lab_object_cmodel');
  
  // Genesequence Collection
  $genesequence_collection = $connection->repository->constructObject('islandora:genesequence_collection');
  $genesequence_collection->owner = 'fedoraAdmin';
  $genesequence_collection->label = 'Genesequence Collection';
  $genesequence_collection->models = 'islandora:collectionCModel';
  $genesequence_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  $datastream = $genesequence_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/collection_policies/islandora_lab_object_genesequence_collection_policy.xml", FALSE);
  $genesequence_collection->ingestDatastream($datastream);

  // add the relationship between genesequences and specimens
  $specimen_model = islandora_object_load("islandora:specimen_cmodel");
 // add_hasPart($specimen_model, "islandora:genesequence_cmodel");
  //add_isPartOf($genesequence_cmodel, "islandora:specimen_cmodel");

  return array(
    'islandora_lab_object_genesequence' => array(
      'title' => 'Bioinformatics Genesequence',
      'objects' => array(
          $genesequence_cmodel,
          $genesequence_collection,
      ),
    ),
  );
}

function islandora_lab_object_genesequence_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_lab_object_genesequence');
  return array(
    'Genesequence Form' => array(
      'form_file' => "$module_path/xml/islandora_lab_object_genesequence_form.xml",
    ),
  );
}

function islandora_lab_object_genesequence_islandora_xml_form_builder_form_associations() {
  $module_path = drupal_get_path('module', 'islandora_lab_object_genesequence');
  return array(
    'islandora_lab_object_genesequence_form' => array(
      'genesequence_cm' => 'islandora:genesequence',
      'form_name' => 'Genesequence Form',
      'dsid' => 'EML',
      'title_field' => array('taxonomy', 'species'),
      'transform' => '',
      //'self_transform' => "$module_path/xml/islandora_lab_object_genesequence_transform.xsl",
      'template' => FALSE,
    ),
  );
}

function islandora_lab_object_genesequence_islandora_genesequence_cmodel_islandora_ingest_steps(array $configuration) {
  return array(
    'islandora_lab_object_genesequence_fasta_file_upload' => array(
      'weight' => 8,
      'type' => 'form',
      'form_id' => 'islandora_lab_object_genesequence_upload_fasta_form',
      'module' => 'islandora_lab_object_genesequence',
      'file' => 'includes/islandora_lab_object_genesequence_upload_fasta.form.inc'
    ),
   /* 'islandora_lab_object_lcms_raw_file_upload' => array(
      'weight' => 9,
      'type' => 'form',
      'form_id' => 'islandora_lab_object_lcms_upload_raw_form',
      'module' => 'islandora_lab_object_lcms',
      'file' => 'includes/islandora_lab_object_lcms_upload_raw.form.inc'
    )*/
  );
}

/*
function islandora_bioinformatics_genesequence_islandora_genesequence_cmodel_islandora_derivatives() {
	return array(
		array(
		  'source_dsid' => 'FASTA',
		  'weight' => '0',
		  'function' => array(
			'islandora_bioinformatics_genesequence_create_fasta_file',
		  ),
		  'file' => drupal_get_path('module', 'islandora_bioinformatics_genesequence') . '/includes/derivatives.inc',
		),
	);
}
*/
