<?php

/**
  * @file
  * islandora_lab_object_genesequence.install
  */

/**
  * Implements hook_install().
  *
  * @see islandora_lab_object_genesequence_islandora_required_objects()
  */
  function islandora_lab_object_genesequence_install() {
    module_load_include('inc', 'islandora', 'includes/solution_packs');
    islandora_install_solution_pack('islandora_lab_object_genesequence');
  }

/**
  * Implements hook_uninstall().
  */
  function islandora_lab_object_genesequence_uninstall() {
    module_load_include('inc', 'islandora', 'includes/solution_packs');
    islandora_install_solution_pack('islandora_lab_object_genesequence', 'uninstall');
    $variables = array('islandora_lab_object_genesequence');
    array_walk($variables, 'variable_del');
  }


